Repository Quantco/dataframely, pull requests merged in 2025-05, with the labels that each got.

#29 fix: Add `dy.Object` to mypy plugin
  dataframely/mypy.py
  tests/test_typing.py
Labels: fix

#27 feat: Add `dy.Array` column type
  dataframely/__init__.py
  dataframely/columns/__init__.py
  dataframely/columns/array.py
  dataframely/mypy.py
  dataframely/testing/__init__.py
  dataframely/testing/const.py
  tests/column_types/test_array.py
  tests/columns/test_default_dtypes.py
  tests/columns/test_pyarrow.py
  tests/columns/test_sample.py
  tests/columns/test_sql_schema.py
  tests/columns/test_str.py
  tests/test_typing.py
Labels: enhancement

#28 ci: Remove lockfile update workflow
  .copier-answers.yml
  .github/workflows/update-lockfiles.yml
Labels: ci

#34 fix: Correctly set dunder name for schemas with at least one rule
  dataframely/_base_schema.py
  tests/schema/test_base.py
Labels: fix

#36 fix: Allow `pipe` to be used on typed data frames
  dataframely/_typing.py
  tests/test_typing.py
Labels: fix

#19 feat: Allow for multiple column level checks with custom naming
  dataframely/columns/_base.py
  dataframely/columns/any.py
  dataframely/columns/array.py
  dataframely/columns/datetime.py
  dataframely/columns/decimal.py
  dataframely/columns/enum.py
  dataframely/columns/float.py
  dataframely/columns/integer.py
  dataframely/columns/list.py
  dataframely/columns/object.py
  dataframely/columns/string.py
  dataframely/columns/struct.py
  tests/columns/test_check.py
Labels: enhancement
