Repository Quantco/dataframely, pull requests merged in 2025-07, with the labels that each got.

#71 feat: Enable custom data frame pre-processing during schema sampling
  dataframely/schema.py
  tests/schema/test_sample.py
Labels: enhancement

#79 fix: Ensure compatibility with polars 1.31
  README.md
  dataframely/testing/rules.py
  pixi.lock
Labels: fix

#66 feat: Introduce functionality to read and write typed parquets
  dataframely/_typing.py
  dataframely/exc.py
  dataframely/schema.py
  pixi.lock
  pixi.toml
  tests/schema/test_read_write_parquet.py
Labels: enhancement

#74 feat: Allow to serialize collections
  dataframely/__init__.py
  dataframely/_serialization.py
  dataframely/collection.py
  dataframely/schema.py
  tests/collection/test_serialization.py
Labels: enhancement

#77 feat: Allow to efficiently read and write collections
  dataframely/collection.py
  dataframely/schema.py
  tests/collection/test_base.py
  tests/collection/test_read_write_parquet.py
Labels: enhancement

#75 feat: Add proper serialization support for failure info
  dataframely/_serialization.py
  dataframely/failure.py
  dataframely/schema.py
  pixi.lock
  tests/test_failure_info.py
Labels: enhancement

#83 fix: Allow to pass custom metadata to failure info parquets
  dataframely/failure.py
  tests/test_failure_info.py
Labels: fix

#84 refactor: Change `Literal[None]` to `None`
  dataframely/_extre.pyi
Labels: refactor

#86 refactor: Move `Validation` to public API
  dataframely/__init__.py
Labels: refactor

#88 build: Support Python 3.10
  .copier-answers.yml
  .github/workflows/build.yml
  .github/workflows/ci.yml
  Cargo.toml
  dataframely/_base_collection.py
  dataframely/_base_schema.py
  dataframely/_rule.py
  dataframely/collection.py
  dataframely/columns/_base.py
  dataframely/columns/_mixins.py
  dataframely/columns/array.py
  dataframely/columns/list.py
  dataframely/columns/struct.py
  dataframely/config.py
  dataframely/schema.py
  pixi.lock
  pixi.toml
  pyproject.toml
  tests/test_typing.py
Labels: build

#89 fix: Only warn about nullability on non-primary-key columns
  dataframely/columns/_base.py
Labels: fix

#104 fix: Remove superfluous warning about superfluous collection members
  dataframely/collection.py
  tests/collection/test_validate_input.py
Labels: fix
