Repository Quantco/dataframely, pull requests merged in 2025-08, with the labels that each got.

#110 chore: Upgrade for polars 1.32
  dataframely/columns/enum.py
  pixi.lock
  pixi.toml
  pyproject.toml
  tests/columns/test_pyarrow.py
Labels: chore

#111 feat: Simplify sampling collections with common primary keys
  dataframely/collection.py
  dataframely/random.py
  tests/collection/test_sample.py
Labels: enhancement

#115 fix: Correctly import optional sqlalchemy dependency
  dataframely/columns/categorical.py
Labels: fix

#116 fix: Correctly deserialize collections from schema
  dataframely/collection.py
  tests/collection/test_serialization.py
Labels: fix

#121 refactor: Ensure `filter` and `validate` maintain order
  dataframely/_rule.py
  dataframely/collection.py
  dataframely/schema.py
  tests/collection/test_filter_validate.py
  tests/schema/test_filter.py
  tests/schema/test_validate.py
Labels: refactor

#127 feat: Add `join` for Collections
  dataframely/_base_collection.py
  dataframely/collection.py
  tests/collection/test_join.py
Labels: enhancement
