Repository Quantco/dataframely, pull requests merged in 2025-04, with the labels that each got.

#1 docs: Add readthedocs link to pyproject/PyPI
  pyproject.toml
Labels: documentation

#3 ci: Fix the "chore" workflow for pull requests from forks
  .github/workflows/chore.yml
Labels: ci

#4 test: Remove warnings emitted in tests
  tests/column_types/test_float.py
  tests/columns/test_rules.py
Labels: test

#6 ci: Add token for uploading code coverage
  .github/workflows/ci.yml
Labels: ci

#5 feat: Allow to inline collection member columns for sampling
  dataframely/_base_collection.py
  dataframely/collection.py
  tests/collection/test_sample.py
Labels: enhancement

#12 feat: Add `dy.Object` column type
  dataframely/__init__.py
  dataframely/columns/__init__.py
  dataframely/columns/object.py
  tests/column_types/test_object.py
  tests/columns/test_sql_schema.py
Labels: enhancement

#8 fix: Allow to make annotated collection members optional
  dataframely/_base_collection.py
  tests/collection/test_implementation.py
  tests/collection/test_sample.py
Labels: fix

#16 fix: Make group rules work on nullable grouping columns
  dataframely/_rule.py
  tests/schema/test_validate.py
Labels: fix

#18 fix: Make enums tolerate multiple sequence types
  dataframely/columns/enum.py
  tests/column_types/test_enum.py
Labels: fix

#22 build: Enable LTO and set codegen units to 1
  Cargo.toml
Labels: build

#24 fix: Generate nulls for Nullable list/struct in `sample`
  dataframely/columns/list.py
  dataframely/columns/struct.py
  dataframely/random.py
  tests/columns/test_sample.py
Labels: fix
